version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./web/dist:/var/www/html/
      - ./static/:/static/
    depends_on:
      - web
  app-pm2:
    container_name: app-pm2
    #构建容器
    build: ./backend
    ports:
    - "3000:3000"
  web:
    container_name: web
    #构建容器
    build: ./web
    volumes：
      - ./web:/usr/src/app
    depends_on:
      - app-pm2
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8000:8081
